export interface Car {
  id: number
  name: string
  type: string
  image: string
  fuel: string
  transmission: string
  capacity: string
  price: number
  originalPrice?: number
  liked: boolean
  description?: string
  rating?: number
  reviewCount?: number
}

export const allCars: Car[] = [
  // Sport cars (10 total)
  {
    id: 1,
    name: "Koenigsegg",
    type: "Sport",
    image: "/new-sports-car.png",
    fuel: "90L",
    transmission: "Manual",
    capacity: "2 People",
    price: 99,
    liked: false,
    description:
      "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.",
    rating: 4.5,
    reviewCount: 440,
  },
  {
    id: 2,
    name: "Nissan GT - R",
    type: "Sport",
    image: "/silver-nissan-gtr-sports-car.png",
    fuel: "80L",
    transmission: "Manual",
    capacity: "2 People",
    price: 80,
    originalPrice: 100,
    liked: true,
    description:
      "NISMO has become the embodiment of Nissan's outstanding performance, inspired by the most unforgiving proving ground, the 'race track'.",
    rating: 4.5,
    reviewCount: 440,
  },
  {
    id: 3,
    name: "Porsche 911",
    type: "Sport",
    image: "/red-porsche-911-sports-car.png",
    fuel: "75L",
    transmission: "Manual",
    capacity: "2 People",
    price: 120,
    liked: false,
    description: "Iconic German sports car with exceptional performance and timeless design.",
    rating: 4.7,
    reviewCount: 380,
  },
  {
    id: 4,
    name: "Ferrari F8",
    type: "Sport",
    image: "/red-ferrari-f8-sports-car.png",
    fuel: "85L",
    transmission: "Manual",
    capacity: "2 People",
    price: 150,
    liked: true,
    description: "Italian masterpiece delivering unmatched speed and luxury.",
    rating: 4.8,
    reviewCount: 520,
  },
  {
    id: 5,
    name: "Lamborghini Huracan",
    type: "Sport",
    image: "/yellow-lamborghini-huracan-sports-car.png",
    fuel: "83L",
    transmission: "Manual",
    capacity: "2 People",
    price: 140,
    liked: false,
    description: "Bold and aggressive supercar with breathtaking performance.",
    rating: 4.6,
    reviewCount: 290,
  },
  {
    id: 6,
    name: "McLaren 720S",
    type: "Sport",
    image: "/orange-mclaren-720s-sports-car.png",
    fuel: "72L",
    transmission: "Manual",
    capacity: "2 People",
    price: 135,
    liked: true,
    description: "British engineering excellence with cutting-edge aerodynamics.",
    rating: 4.7,
    reviewCount: 310,
  },
  {
    id: 7,
    name: "Audi R8",
    type: "Sport",
    image: "/blue-audi-r8-sports-car.png",
    fuel: "80L",
    transmission: "Manual",
    capacity: "2 People",
    price: 110,
    liked: false,
    description: "German precision meets supercar performance in this stunning machine.",
    rating: 4.4,
    reviewCount: 270,
  },
  {
    id: 8,
    name: "BMW M8",
    type: "Sport",
    image: "/black-bmw-m8-sports-car.png",
    fuel: "78L",
    transmission: "Manual",
    capacity: "2 People",
    price: 105,
    liked: true,
    description: "Luxury meets performance in this sophisticated sports coupe.",
    rating: 4.3,
    reviewCount: 240,
  },
  {
    id: 9,
    name: "Mercedes AMG GT",
    type: "Sport",
    image: "/silver-mercedes-amg-gt-sports-car.png",
    fuel: "76L",
    transmission: "Manual",
    capacity: "2 People",
    price: 115,
    liked: false,
    description: "German luxury and performance combined in perfect harmony.",
    rating: 4.5,
    reviewCount: 330,
  },
  {
    id: 10,
    name: "Chevrolet Corvette",
    type: "Sport",
    image: "/red-chevrolet-corvette-sports-car.png",
    fuel: "74L",
    transmission: "Manual",
    capacity: "2 People",
    price: 95,
    liked: true,
    description: "American muscle meets modern technology in this iconic sports car.",
    rating: 4.2,
    reviewCount: 200,
  },

  // SUV cars (12 total)
  {
    id: 11,
    name: "All New Rush",
    type: "SUV",
    image: "/placeholder-rush.png",
    fuel: "70L",
    transmission: "Manual",
    capacity: "6 People",
    price: 72,
    originalPrice: 80,
    liked: false,
    description: "A reliable and spacious SUV perfect for family adventures and daily commuting needs.",
    rating: 4.2,
    reviewCount: 280,
  },
  {
    id: 12,
    name: "CR - V",
    type: "SUV",
    image: "/placeholder-crv.png",
    fuel: "80L",
    transmission: "Manual",
    capacity: "6 People",
    price: 80,
    liked: true,
    description: "Honda's popular SUV offering excellent fuel efficiency and comfortable seating for the whole family.",
    rating: 4.4,
    reviewCount: 350,
  },
  {
    id: 13,
    name: "All New Terios",
    type: "SUV",
    image: "/placeholder-terios.png",
    fuel: "90L",
    transmission: "Manual",
    capacity: "6 People",
    price: 74,
    liked: false,
    description: "A compact SUV that combines style, comfort, and practicality for urban and outdoor adventures.",
    rating: 4.1,
    reviewCount: 220,
  },
  {
    id: 14,
    name: "New MG ZS",
    type: "SUV",
    image: "/placeholder-mgzs.png",
    fuel: "80L",
    transmission: "Manual",
    capacity: "6 People",
    price: 80,
    liked: false,
    description: "A modern SUV with advanced features and comfortable interior for all your travel needs.",
    rating: 4.2,
    reviewCount: 260,
  },
  {
    id: 15,
    name: "Toyota RAV4",
    type: "SUV",
    image: "/white-toyota-rav4-suv.png",
    fuel: "75L",
    transmission: "CVT",
    capacity: "5 People",
    price: 85,
    liked: true,
    description: "Reliable and efficient SUV perfect for both city and off-road adventures.",
    rating: 4.3,
    reviewCount: 420,
  },
  {
    id: 16,
    name: "Ford Explorer",
    type: "SUV",
    image: "/blue-ford-explorer-suv.png",
    fuel: "85L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 90,
    liked: false,
    description: "Spacious family SUV with advanced safety features and comfortable seating.",
    rating: 4.1,
    reviewCount: 310,
  },
  {
    id: 17,
    name: "Jeep Grand Cherokee",
    type: "SUV",
    image: "/black-jeep-grand-cherokee-suv.png",
    fuel: "88L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 95,
    liked: true,
    description: "Rugged SUV with exceptional off-road capabilities and premium interior.",
    rating: 4.4,
    reviewCount: 380,
  },
  {
    id: 18,
    name: "BMW X5",
    type: "SUV",
    image: "/silver-bmw-x5-suv.png",
    fuel: "82L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 120,
    liked: false,
    description: "Luxury SUV combining performance, comfort, and advanced technology.",
    rating: 4.5,
    reviewCount: 290,
  },
  {
    id: 19,
    name: "Audi Q7",
    type: "SUV",
    image: "/white-audi-q7-suv.png",
    fuel: "85L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 115,
    liked: true,
    description: "Premium SUV with sophisticated design and cutting-edge features.",
    rating: 4.6,
    reviewCount: 340,
  },
  {
    id: 20,
    name: "Mercedes GLE",
    type: "SUV",
    image: "/gray-mercedes-gle-suv.png",
    fuel: "80L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 110,
    liked: false,
    description: "Elegant SUV offering luxury, performance, and advanced safety systems.",
    rating: 4.4,
    reviewCount: 270,
  },
  {
    id: 21,
    name: "Volvo XC90",
    type: "SUV",
    image: "/blue-volvo-xc90-suv.png",
    fuel: "78L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 105,
    liked: true,
    description: "Scandinavian luxury SUV with exceptional safety and comfort features.",
    rating: 4.5,
    reviewCount: 320,
  },
  {
    id: 22,
    name: "Lexus RX",
    type: "SUV",
    image: "/red-lexus-rx-suv.png",
    fuel: "76L",
    transmission: "CVT",
    capacity: "5 People",
    price: 100,
    liked: false,
    description: "Reliable luxury SUV with hybrid efficiency and premium amenities.",
    rating: 4.3,
    reviewCount: 250,
  },

  // Sedan cars (20 total)
  {
    id: 23,
    name: "Rolls - Royce",
    type: "Sedan",
    image: "/placeholder-owzqh.png",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    price: 96,
    liked: false,
    description: "Experience luxury and comfort with this premium sedan that offers exceptional performance and style.",
    rating: 4.8,
    reviewCount: 320,
  },
  {
    id: 24,
    name: "BMW 3 Series",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "65L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 75,
    liked: true,
    description: "The ultimate driving machine with perfect balance of performance and luxury.",
    rating: 4.4,
    reviewCount: 450,
  },
  {
    id: 25,
    name: "Mercedes C-Class",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 80,
    liked: false,
    description: "Sophisticated sedan combining elegance with cutting-edge technology.",
    rating: 4.5,
    reviewCount: 380,
  },
  {
    id: 26,
    name: "Audi A4",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "66L",
    transmission: "CVT",
    capacity: "5 People",
    price: 78,
    liked: true,
    description: "Premium sedan with advanced quattro all-wheel drive and luxurious interior.",
    rating: 4.3,
    reviewCount: 340,
  },
  {
    id: 27,
    name: "Toyota Camry",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "70L",
    transmission: "CVT",
    capacity: "5 People",
    price: 65,
    liked: false,
    description: "Reliable and efficient sedan perfect for daily commuting and family use.",
    rating: 4.2,
    reviewCount: 520,
  },
  {
    id: 28,
    name: "Honda Accord",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "CVT",
    capacity: "5 People",
    price: 68,
    liked: true,
    description: "Spacious and fuel-efficient sedan with advanced safety features.",
    rating: 4.1,
    reviewCount: 480,
  },
  {
    id: 29,
    name: "Lexus ES",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "65L",
    transmission: "CVT",
    capacity: "5 People",
    price: 85,
    liked: false,
    description: "Luxury sedan offering exceptional comfort and hybrid efficiency.",
    rating: 4.4,
    reviewCount: 290,
  },
  {
    id: 30,
    name: "Genesis G90",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "75L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 110,
    liked: true,
    description: "Ultra-luxury sedan with premium materials and advanced technology.",
    rating: 4.6,
    reviewCount: 180,
  },
  {
    id: 31,
    name: "Cadillac CT5",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "72L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 88,
    liked: false,
    description: "American luxury sedan with bold design and powerful performance.",
    rating: 4.2,
    reviewCount: 220,
  },
  {
    id: 32,
    name: "Volvo S90",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "70L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 92,
    liked: true,
    description: "Scandinavian luxury sedan with exceptional safety and comfort.",
    rating: 4.3,
    reviewCount: 260,
  },
  {
    id: 33,
    name: "Infiniti Q50",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "74L",
    transmission: "CVT",
    capacity: "5 People",
    price: 82,
    liked: false,
    description: "Sport luxury sedan with innovative technology and dynamic performance.",
    rating: 4.1,
    reviewCount: 200,
  },
  {
    id: 34,
    name: "Acura TLX",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 76,
    liked: true,
    description: "Performance sedan with precision all-wheel steer and premium features.",
    rating: 4.0,
    reviewCount: 240,
  },
  {
    id: 35,
    name: "Jaguar XE",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "66L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 90,
    liked: false,
    description: "British luxury sedan with distinctive design and engaging driving dynamics.",
    rating: 4.2,
    reviewCount: 170,
  },
  {
    id: 36,
    name: "Alfa Romeo Giulia",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "64L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 85,
    liked: true,
    description: "Italian sport sedan with passionate design and thrilling performance.",
    rating: 4.3,
    reviewCount: 150,
  },
  {
    id: 37,
    name: "Maserati Ghibli",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "78L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 125,
    liked: false,
    description: "Italian luxury sedan with distinctive style and powerful engine options.",
    rating: 4.4,
    reviewCount: 130,
  },
  {
    id: 38,
    name: "Tesla Model S",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "Electric",
    transmission: "Electric",
    capacity: "5 People",
    price: 135,
    liked: true,
    description: "Revolutionary electric sedan with autopilot and incredible acceleration.",
    rating: 4.5,
    reviewCount: 380,
  },
  {
    id: 39,
    name: "Porsche Panamera",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "80L",
    transmission: "Automatic",
    capacity: "4 People",
    price: 145,
    liked: false,
    description: "Sports car performance in a luxury sedan package.",
    rating: 4.6,
    reviewCount: 210,
  },
  {
    id: 40,
    name: "Bentley Flying Spur",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "90L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 200,
    liked: true,
    description: "Ultra-luxury sedan with handcrafted interior and powerful W12 engine.",
    rating: 4.8,
    reviewCount: 95,
  },
  {
    id: 41,
    name: "Chrysler 300",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "76L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 70,
    liked: false,
    description: "Full-size sedan with bold American styling and spacious interior.",
    rating: 3.9,
    reviewCount: 280,
  },
  {
    id: 42,
    name: "Kia Stinger",
    type: "Sedan",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "72L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 73,
    liked: true,
    description: "Sport sedan with rear-wheel drive and impressive performance credentials.",
    rating: 4.1,
    reviewCount: 190,
  },

  // Coupe cars (14 total)
  {
    id: 43,
    name: "BMW M4",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "Manual",
    capacity: "4 People",
    price: 105,
    liked: true,
    description: "High-performance coupe with track-bred capabilities and luxury appointments.",
    rating: 4.5,
    reviewCount: 280,
  },
  {
    id: 44,
    name: "Mercedes C63 AMG",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "70L",
    transmission: "Automatic",
    capacity: "4 People",
    price: 115,
    liked: false,
    description: "Powerful coupe with handcrafted AMG engine and aggressive styling.",
    rating: 4.6,
    reviewCount: 240,
  },
  {
    id: 45,
    name: "Audi RS5",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "66L",
    transmission: "Automatic",
    capacity: "4 People",
    price: 110,
    liked: true,
    description: "Sport coupe with quattro all-wheel drive and stunning design.",
    rating: 4.4,
    reviewCount: 220,
  },
  {
    id: 46,
    name: "Lexus RC F",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "72L",
    transmission: "Automatic",
    capacity: "4 People",
    price: 100,
    liked: false,
    description: "Japanese performance coupe with naturally aspirated V8 engine.",
    rating: 4.2,
    reviewCount: 180,
  },
  {
    id: 47,
    name: "Cadillac ATS",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "64L",
    transmission: "Manual",
    capacity: "4 People",
    price: 85,
    liked: true,
    description: "Compact luxury coupe with sharp handling and bold American design.",
    rating: 4.0,
    reviewCount: 160,
  },
  {
    id: 48,
    name: "Infiniti Q60",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "CVT",
    capacity: "4 People",
    price: 90,
    liked: false,
    description: "Luxury sport coupe with distinctive design and advanced technology.",
    rating: 4.1,
    reviewCount: 140,
  },
  {
    id: 49,
    name: "Genesis G70",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "65L",
    transmission: "Manual",
    capacity: "4 People",
    price: 88,
    liked: true,
    description: "Luxury sport coupe with rear-wheel drive and premium interior.",
    rating: 4.3,
    reviewCount: 170,
  },
  {
    id: 50,
    name: "Dodge Challenger",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "76L",
    transmission: "Manual",
    capacity: "4 People",
    price: 78,
    liked: false,
    description: "American muscle coupe with retro styling and powerful engine options.",
    rating: 4.2,
    reviewCount: 320,
  },
  {
    id: 51,
    name: "Chevrolet Camaro",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "74L",
    transmission: "Manual",
    capacity: "4 People",
    price: 75,
    liked: true,
    description: "Iconic American muscle car with aggressive styling and track performance.",
    rating: 4.1,
    reviewCount: 290,
  },
  {
    id: 52,
    name: "Ford Mustang",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "72L",
    transmission: "Manual",
    capacity: "4 People",
    price: 72,
    liked: false,
    description: "America's favorite pony car with timeless design and thrilling performance.",
    rating: 4.0,
    reviewCount: 410,
  },
  {
    id: 53,
    name: "Subaru BRZ",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "60L",
    transmission: "Manual",
    capacity: "4 People",
    price: 65,
    liked: true,
    description: "Pure sports coupe with rear-wheel drive and perfect weight balance.",
    rating: 4.2,
    reviewCount: 250,
  },
  {
    id: 54,
    name: "Toyota 86",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "62L",
    transmission: "Manual",
    capacity: "4 People",
    price: 68,
    liked: false,
    description: "Affordable sports coupe designed for driving enthusiasts.",
    rating: 4.1,
    reviewCount: 230,
  },
  {
    id: 55,
    name: "Hyundai Genesis Coupe",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "70L",
    transmission: "Manual",
    capacity: "4 People",
    price: 70,
    liked: true,
    description: "Rear-wheel drive coupe with turbocharged performance and value pricing.",
    rating: 3.9,
    reviewCount: 200,
  },
  {
    id: 56,
    name: "Nissan 370Z",
    type: "Coupe",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "66L",
    transmission: "Manual",
    capacity: "2 People",
    price: 80,
    liked: false,
    description: "Japanese sports coupe with naturally aspirated V6 and sharp handling.",
    rating: 4.0,
    reviewCount: 180,
  },

  // Hatchback cars (14 total)
  {
    id: 57,
    name: "MG ZX Exclusive",
    type: "Hatchback",
    image: "/placeholder-mg.png",
    fuel: "70L",
    transmission: "Electric",
    capacity: "4 People",
    price: 76,
    originalPrice: 80,
    liked: true,
    description: "An innovative electric hatchback that delivers exceptional performance with zero emissions.",
    rating: 4.3,
    reviewCount: 190,
  },
  {
    id: 58,
    name: "MG ZX Excite",
    type: "Hatchback",
    image: "/placeholder-mgex.png",
    fuel: "90L",
    transmission: "Manual",
    capacity: "4 People",
    price: 74,
    originalPrice: 80,
    liked: true,
    description: "A stylish and efficient hatchback perfect for city driving and weekend getaways.",
    rating: 4.0,
    reviewCount: 180,
  },
  {
    id: 59,
    name: "Volkswagen Golf GTI",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "55L",
    transmission: "Manual",
    capacity: "5 People",
    price: 68,
    liked: false,
    description: "The original hot hatch with turbocharged performance and refined handling.",
    rating: 4.4,
    reviewCount: 380,
  },
  {
    id: 60,
    name: "Honda Civic Type R",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "50L",
    transmission: "Manual",
    capacity: "5 People",
    price: 75,
    liked: true,
    description: "Track-focused hot hatch with aggressive styling and incredible performance.",
    rating: 4.5,
    reviewCount: 290,
  },
  {
    id: 61,
    name: "Ford Focus ST",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "52L",
    transmission: "Manual",
    capacity: "5 People",
    price: 65,
    liked: false,
    description: "Performance hatchback with turbocharged engine and sport-tuned suspension.",
    rating: 4.2,
    reviewCount: 250,
  },
  {
    id: 62,
    name: "Subaru WRX STI",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "60L",
    transmission: "Manual",
    capacity: "5 People",
    price: 82,
    liked: true,
    description: "Rally-bred performance hatchback with all-wheel drive and turbo power.",
    rating: 4.3,
    reviewCount: 320,
  },
  {
    id: 63,
    name: "Hyundai i30 N",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "50L",
    transmission: "Manual",
    capacity: "5 People",
    price: 62,
    liked: false,
    description: "Korean hot hatch with track-inspired performance and aggressive styling.",
    rating: 4.1,
    reviewCount: 180,
  },
  {
    id: 64,
    name: "Renault Megane RS",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "53L",
    transmission: "Manual",
    capacity: "5 People",
    price: 70,
    liked: true,
    description: "French hot hatch with sophisticated chassis and turbocharged performance.",
    rating: 4.2,
    reviewCount: 160,
  },
  {
    id: 65,
    name: "SEAT Leon Cupra",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "55L",
    transmission: "Manual",
    capacity: "5 People",
    price: 66,
    liked: false,
    description: "Spanish performance hatchback with turbocharged power and sharp handling.",
    rating: 4.0,
    reviewCount: 140,
  },
  {
    id: 66,
    name: "Audi RS3",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "58L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 95,
    liked: true,
    description: "Luxury hot hatch with five-cylinder turbo engine and quattro all-wheel drive.",
    rating: 4.5,
    reviewCount: 220,
  },
  {
    id: 67,
    name: "BMW M135i",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "52L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 85,
    liked: false,
    description: "Premium hot hatch with all-wheel drive and refined performance.",
    rating: 4.3,
    reviewCount: 200,
  },
  {
    id: 68,
    name: "Mercedes A45 AMG",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "50L",
    transmission: "Automatic",
    capacity: "5 People",
    price: 90,
    liked: true,
    description: "High-performance luxury hatchback with AMG engineering and all-wheel drive.",
    rating: 4.4,
    reviewCount: 180,
  },
  {
    id: 69,
    name: "Mini Cooper S",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "44L",
    transmission: "Manual",
    capacity: "4 People",
    price: 58,
    liked: false,
    description: "Iconic British hatchback with go-kart handling and distinctive style.",
    rating: 4.1,
    reviewCount: 280,
  },
  {
    id: 70,
    name: "Mazda3 MPS",
    type: "Hatchback",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "55L",
    transmission: "Manual",
    capacity: "5 People",
    price: 64,
    liked: true,
    description: "Japanese hot hatch with turbocharged performance and premium interior.",
    rating: 4.0,
    reviewCount: 160,
  },

  // MPV cars (16 total)
  {
    id: 71,
    name: "Toyota Sienna",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "75L",
    transmission: "CVT",
    capacity: "8 People",
    price: 85,
    liked: false,
    description: "Spacious family minivan with hybrid efficiency and all-wheel drive capability.",
    rating: 4.2,
    reviewCount: 320,
  },
  {
    id: 72,
    name: "Honda Odyssey",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "70L",
    transmission: "Automatic",
    capacity: "8 People",
    price: 82,
    liked: true,
    description: "Premium minivan with innovative seating and advanced safety features.",
    rating: 4.3,
    reviewCount: 290,
  },
  {
    id: 73,
    name: "Chrysler Pacifica",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "Automatic",
    capacity: "8 People",
    price: 78,
    liked: false,
    description: "Modern minivan with stylish design and family-friendly features.",
    rating: 4.1,
    reviewCount: 250,
  },
  {
    id: 74,
    name: "Kia Carnival",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "72L",
    transmission: "Automatic",
    capacity: "8 People",
    price: 75,
    liked: true,
    description: "Versatile MPV with SUV-like styling and spacious interior.",
    rating: 4.0,
    reviewCount: 180,
  },
  {
    id: 75,
    name: "Volkswagen Sharan",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "70L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 80,
    liked: false,
    description: "European MPV with premium build quality and flexible seating.",
    rating: 4.2,
    reviewCount: 160,
  },
  {
    id: 76,
    name: "Ford Galaxy",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "68L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 76,
    liked: true,
    description: "Large MPV with comfortable seating and practical design.",
    rating: 4.0,
    reviewCount: 140,
  },
  {
    id: 77,
    name: "SEAT Alhambra",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "66L",
    transmission: "Manual",
    capacity: "7 People",
    price: 72,
    liked: false,
    description: "Spanish MPV with efficient engines and spacious cabin.",
    rating: 3.9,
    reviewCount: 120,
  },
  {
    id: 78,
    name: "Renault Espace",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "64L",
    transmission: "CVT",
    capacity: "7 People",
    price: 74,
    liked: true,
    description: "French MPV with innovative design and comfortable ride.",
    rating: 4.1,
    reviewCount: 130,
  },
  {
    id: 79,
    name: "Peugeot 5008",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "62L",
    transmission: "Automatic",
    capacity: "7 People",
    price: 70,
    liked: false,
    description: "Stylish French MPV with SUV-inspired design and efficient engines.",
    rating: 4.0,
    reviewCount: 110,
  },
  {
    id: 80,
    name: "Citroen Grand C4 Picasso",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "60L",
    transmission: "Manual",
    capacity: "7 People",
    price: 68,
    liked: true,
    description: "Innovative French MPV with panoramic windscreen and flexible interior.",
    rating: 3.8,
    reviewCount: 100,
  },
  {
    id: 81,
    name: "Opel Zafira",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "58L",
    transmission: "Manual",
    capacity: "7 People",
    price: 65,
    liked: false,
    description: "Compact MPV with efficient packaging and practical features.",
    rating: 3.9,
    reviewCount: 150,
  },
  {
    id: 82,
    name: "Mazda5",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "55L",
    transmission: "Manual",
    capacity: "6 People",
    price: 62,
    liked: true,
    description: "Compact MPV with sliding doors and sporty handling.",
    rating: 4.0,
    reviewCount: 140,
  },
  {
    id: 83,
    name: "Mitsubishi Grandis",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "65L",
    transmission: "CVT",
    capacity: "7 People",
    price: 66,
    liked: false,
    description: "Japanese MPV with reliable engineering and spacious interior.",
    rating: 3.8,
    reviewCount: 90,
  },
  {
    id: 84,
    name: "Hyundai i800",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "75L",
    transmission: "Manual",
    capacity: "8 People",
    price: 70,
    liked: true,
    description: "Large Korean MPV with commercial vehicle practicality and passenger comfort.",
    rating: 3.9,
    reviewCount: 80,
  },
  {
    id: 85,
    name: "Nissan NV200",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "55L",
    transmission: "Manual",
    capacity: "7 People",
    price: 58,
    liked: false,
    description: "Compact commercial MPV with excellent fuel economy and cargo space.",
    rating: 3.7,
    reviewCount: 70,
  },
  {
    id: 86,
    name: "Mercedes V-Class",
    type: "MPV",
    image: "/placeholder.svg?height=200&width=300",
    fuel: "80L",
    transmission: "Automatic",
    capacity: "8 People",
    price: 120,
    liked: true,
    description: "Luxury MPV with premium materials and advanced technology.",
    rating: 4.4,
    reviewCount: 160,
  },
]

export function getCarById(id: number): Car | undefined {
  return allCars.find((car) => car.id === id)
}
